### PR TITLE
replaced 'user' in cmd.* invocations to 'runas'

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by lsh-0** [comment]
this is interesting
```
[2020-02-24T05:41:42.455Z] [54.90.112.240] out: ----------
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:           ID: sciencebeam-texture-docker-containers
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:     Function: cmd.run
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:         Name: /usr/local/bin/docker-compose up --force-recreate -d
[2020-02-24T05:41:42.455Z] [54.90.112.240] out: 
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:       Result: False
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:      Comment: Command "/usr/local/bin/docker-compose up --force-recreate -d
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:               " run
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:      Started: 05:40:31.960789
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:     Duration: 62236.559 ms
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:      Changes:   
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:               ----------
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:               pid:
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:                   23155
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:               retcode:
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:                   1
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:               stderr:
[2020-02-24T05:41:42.455Z] [54.90.112.240] out:                   Creating network "sciencebeam-texture_default" with the default driver
[2020-02-24T05:41:42.456Z] [54.90.112.240] out:                   Creating network "sciencebeam-texture_grobid" with the default driver
[2020-02-24T05:41:42.456Z] [54.90.112.240] out:                   Pulling sciencebeam-autocut (elifesciences/sciencebeam-gym-autocut_trained:40ff412896fc3b5077803c759beaf92f3e8970cb-elife-author-submitted-pdf-train-1000)...
[2020-02-24T05:41:42.456Z] [54.90.112.240] out:                   Pulling grobid (lfoppiano/grobid:0.5.3)...
[2020-02-24T05:41:42.456Z] [54.90.112.240] out:                   no such image: elifesciences/sciencebeam:b'0.0.6': invalid reference format
[2020-02-24T05:41:42.456Z] [54.90.112.240] out:               stdout:
[2020-02-24T05:41:42.456Z] [54.90.112.240] out:                   40ff412896fc3b5077803c759beaf92f3e8970cb-elife-author-submitted-pdf-train-1000: Pulling from elifesciences/sciencebeam-gym-autocut_trained
[2020-02-24T05:41:42.456Z] [54.90.112.240] out:                   Digest: sha256:fdf470ee49c931626e02c36d343d4185459fd35f6a44ece49ab2cabc5532bcf2
[2020-02-24T05:41:42.456Z] [54.90.112.240] out:                   Status: Downloaded newer image for elifesciences/sciencebeam-gym-autocut_trained:40ff412896fc3b5077803c759beaf92f3e8970cb-elife-author-submitted-pdf-train-1000
[2020-02-24T05:41:42.456Z] [54.90.112.240] out:                   0.5.3: Pulling from lfoppiano/grobid
[2020-02-24T05:41:42.456Z] [54.90.112.240] out:                   Digest: sha256:71714d54edc02894cc2d8d4fec56a8a005956daf172fe34c7ccfc46d475ec108
[2020-02-24T05:41:42.456Z] [54.90.112.240] out:                   Status: Downloaded newer image for lfoppiano/grobid:0.5.3
```

specifically this: 

> no such image: elifesciences/sciencebeam:b'0.0.6': invalid reference format

**Comment by lsh-0** [comment]
from the docker-compose file, it looks like IMAGE_TAG is coming from the [Jenkinsfile](https://github.com/elifesciences/sciencebeam-texture/blob/develop/Jenkinsfile#L8), which is calling `elifeGitRevision`, which is weird because the `b'...'` is a python bytestring, not a groovy whatever. 

Further down the rabbit hole is this commit: https://github.com/elifesciences/elife-jenkins-workflow-libs/commit/c34bc25d746382a0b07d42aee0c810bf9ffdbdc8

Which makes me think what the contents of this file `"${env.BUILD_TAG}.commit.txt"` contains a python `repr(b"foo")` type string. I can't figure out what is writing that file though.

Any insight @giorgiosironi ?

**Comment by giorgiosironi** [comment]
That `Jenkinsfile` shouldn't be used here.

**Comment by giorgiosironi** [comment]
To disambiguate, this is the `docker-compose` file: https://github.com/elifesciences/sciencebeam-texture-formula/blob/master/salt/sciencebeam-texture/config/home-deployuser-sciencebeam-texture-docker-compose.yml

**Comment by giorgiosironi** [comment]
Which takes the `IMAGE_TAG` from here:
https://github.com/elifesciences/sciencebeam-texture-formula/blob/master/salt/sciencebeam-texture/config/home-deployuser-sciencebeam-texture-.env#L2
where it is rendered by Jinja.

**Comment by lsh-0** [comment]
ah, I see it now:

> communicate() returns a tuple (stdout_data, stderr_data). The data will be strings if streams were opened in text mode; otherwise, bytes.

https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate

**Comment by lsh-0** [comment]
fix: https://github.com/elifesciences/builder-base-formula/pull/281

I'll merge it if it's green, then kick this build

update: builder-base was green, have merged, kicking ...

**Comment by lsh-0** [comment]
> failed to register layer: Error processing tar file(exit status 1): write /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1: no space left on device

next new problem, investigating

**Comment by lsh-0** [comment]
external volume isn't being formatted and mounted. weird. 

```
elife@20200227-1--sciencebeam-texture:~/sciencebeam-texture$ lsblk
NAME    MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
xvda    202:0    0   8G  0 disk 
└─xvda1 202:1    0   8G  0 part /
xvdh    202:112  0  10G  0 disk 
elife@20200227-1--sciencebeam-texture:~/sciencebeam-texture$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G     0  2.0G   0% /dev
tmpfs           396M  5.6M  390M   2% /run
/dev/xvda1      7.7G  6.1G  1.7G  79% /
tmpfs           2.0G   16K  2.0G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
tmpfs           396M     0  396M   0% /run/user/1001
```

from builder-configuration:

```
    'sciencebeam-texture--*':
        - elife.external-volume
```

ahhhhhh - the project formula had fallen out of sync with builder-config. lets see what happens now ...

update: fresh is building now but failing smoke tests

update2: can't replicate failing smoke tests, kicking build, crossing fingers

**Comment by lsh-0** [comment]
smoke tests are now working but container appears unhealthy

I can't replicate this on my own masterless instance

**Comment by lsh-0** [comment]
cc @de-code , you might have some insight into why this is failing it's smoke tests.

`pr-base` (base formula, i.e., no changes) [is broken out of the box](https://github.com/elifesciences/sciencebeam-texture-formula/pull/16), but the fixes I have here should get `fresh` (this branch, built from scratch) green.

**Comment by de-code** [comment]
Is the space issue the problem?

```
[2020-02-27T05:35:13.954Z] [18.209.62.86] out:                   Pulling sciencebeam (elifesciences/sciencebeam:0.0.6)...

[2020-02-27T05:35:13.954Z] [18.209.62.86] out:                   failed to register layer: Error processing tar file(exit status 1): write /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1: no space left on device
```

**Comment by lsh-0** [comment]
> Is the space issue the problem?

only on `base`, as I mentioned. The space issue has been fixed. We're interested in why `fresh` is failing it's smoketests: https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fsciencebeam-texture-formula/detail/PR-15/6/pipeline/27

I'll take another look today with fresher eyes, but failing in the smoke tests means the containerised app is in a bad way.

**Comment by lsh-0** [comment]
huh, that's weird. It looks like the healthchecks passed but the script still failed

```

[2020-02-28T05:06:07.037Z] [3.85.190.248] run: smoke-tests /home/elife/sciencebeam-texture
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: Healthchecks
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: starting
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: sciencebeam-texture_texture_1 is in state: healthy
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: Texture container
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: > localhost:4000/
[2020-02-28T05:06:07.037Z] [3.85.190.248] out:     [ OK ] 2xx Response code
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: Exit code of /usr/local/bin/smoke-tests: 1
[2020-02-28T05:06:07.037Z] [3.85.190.248] out: 
[2020-02-28T05:06:07.037Z] 
[2020-02-28T05:06:07.037Z] ERROR - cfn - One or more hosts failed while executing task 'single_node_work'
[2020-02-28T05:06:07.037Z] 
[2020-02-28T05:06:07.037Z] Underlying exception:
[2020-02-28T05:06:07.037Z]     run() received nonzero return code 1 while executing!
[2020-02-28T05:06:07.037Z]     
[2020-02-28T05:06:07.037Z]     Requested: smoke-tests /home/elife/sciencebeam-texture
[2020-02-28T05:06:07.037Z]     Executed: /bin/bash -l -c "smoke-tests /home/elife/sciencebeam-texture"
[2020-02-28T05:06:07.037Z] exception while executing task 'cmd': 2
```

**Comment by lsh-0** [comment]
hoho - I can replicate this in vagrant (somehow). investigating ..

edit: we're using a third party bash script for smoke tests so figuring out what it's logic is

```
+ '[' 1 '!=' 1 ']'
+ folder=/home/elife/sciencebeam-texture
+ '[' '!' -d /home/elife/sciencebeam-texture ']'
+ cd /home/elife/sciencebeam-texture
+ code=0
+ '[' -e ./smoke_tests.sh ']'
+ ./smoke_tests.sh
+++ mktemp -d
++ SMOKE_TMP_DIR=/tmp/tmp.Nal2x4cSBt
++ SMOKE_AFTER_RESPONSE=
++ SMOKE_CURL_CODE=/tmp/tmp.Nal2x4cSBt/smoke_curl_code
++ SMOKE_CURL_HEADERS=/tmp/tmp.Nal2x4cSBt/smoke_curl_headers
++ SMOKE_CURL_BODY=/tmp/tmp.Nal2x4cSBt/smoke_curl_body
++ SMOKE_CURL_COOKIE_JAR=/tmp/tmp.Nal2x4cSBt/smoke_curl_cookie_jar
++ SMOKE_CSRF_TOKEN=
++ SMOKE_CSRF_FORM_DATA=/tmp/tmp.Nal2x4cSBt/smoke_csrf_form_data
++ SMOKE_TESTS_FAILED=0
++ SMOKE_TESTS_RUN=0
++ SMOKE_URL_PREFIX=
++ SMOKE_HEADER_HOST=
++ '[' -t 1 ']'
+++ tput colors
++ ncolors=256
++ test -n 256
++ test 256 -ge 8
+++ tput bold
++ bold=''
+++ tput sgr0
++ normal=''
+++ tput setaf 1
++ red=''
+++ tput setab 1
++ redbg=''
+++ tput setaf 2
++ green=''
+++ tput setab 2
++ greenbg=''
+ echo Healthchecks
Healthchecks
+ docker-wait-healthy sciencebeam-texture_texture_1
sciencebeam-texture_texture_1 is in state: healthy
+ echo 'Texture container'
Texture container
+ smoke_url_ok localhost:4000/
+ URL=localhost:4000/
+ smoke_url localhost:4000/
+ URL=localhost:4000/
+ _curl_get localhost:4000/
+ URL=localhost:4000/
+ SMOKE_URL=localhost:4000/
+ _smoke_print_url localhost:4000/
+ TEXT=localhost:4000/
+ echo '> localhost:4000/'
> localhost:4000/
+ _curl localhost:4000/
+ opt=(--cookie $SMOKE_CURL_COOKIE_JAR --cookie-jar $SMOKE_CURL_COOKIE_JAR --location --dump-header $SMOKE_CURL_HEADERS --silent)
+ local opt
+ [[ -n '' ]]
+ curl --cookie /tmp/tmp.Nal2x4cSBt/smoke_curl_cookie_jar --cookie-jar /tmp/tmp.Nal2x4cSBt/smoke_curl_cookie_jar --location --dump-header /tmp/tmp.Nal2x4cSBt/smoke_curl_headers --silent localhost:4000/
+ grep -oE 'HTTP[^ ]+ [0-9]{3}' /tmp/tmp.Nal2x4cSBt/smoke_curl_headers
+ grep -oE '[0-9]{3}'
+ tail -n1
+ smoke_assert_code_ok
++ cat /tmp/tmp.Nal2x4cSBt/smoke_curl_code
+ CODE=200
+ [[ 200 == 2* ]]
+ _smoke_success '2xx Response code'
+ REASON='2xx Response code'
+ _smoke_print_success '2xx Response code'
+ TEXT='2xx Response code'
+ echo '    [ OK ] 2xx Response code'
    [ OK ] 2xx Response code
+ ((  SMOKE_TESTS_RUN++  ))
+ code=1
+ echo 'Exit code of /usr/local/bin/smoke-tests: 1'
Exit code of /usr/local/bin/smoke-tests: 1
+ exit 1
```

update: turns out I disabled the wrong thing >:(

**Comment by lsh-0** [comment]
nope, no luck. We're back to an unhealthy container and failing health checks.

This is holding up a lot of other work so I'm going to leave it for now and get on with things

**Comment by de-code** [comment]
Okay, apologies, didn't read all of the messages properly.

So I am assuming that it is now failing within `docker-wait-healthy sciencebeam-texture_texture_1` because it's `unhealthy`. Can we change `docker-wait-healthy` to show the logs of the container in question? (in the failure case)
Otherwise it's difficult to guess why it's unhealthy.

EDIT: alternatively [smoke-tests.sh](https://github.com/elifesciences/sciencebeam-texture-formula/blob/master/salt/sciencebeam-texture/config/home-deployuser-sciencebeam-texture-smoke_tests.sh) could be changed to show the logs. But I guess it's generally useful to show the logs of the container that is failing.

**Comment by lsh-0** [comment]
it looks like the problems I'm seeing here are not new and are being addressed elsewhere:

* https://github.com/elifesciences/sciencebeam-texture-formula/pull/14
* https://github.com/elifesciences/builder-base-formula/pull/253

I'm going to remove the external volume and timeout changes I've made and merge this PR in broken, as it will inevitably be. I'll then bump the other PR with changes from master and see what happens.

**Pull request merged**
